### ISSUE TITLE
Missing articles in modal windows

### ISSUE THREAD

**Issue by esedic** [AlekVolsk/mod_articles_custom#1]
Is this work in progress?
There are no articles in modal window (Select or Change article).

**Comment by AlekVolsk** [comment]
The article's selection field is taken from com_content, where it is intended only for use in a menu item and is not intended to be used in a subform type field.

The logic of use is as follows:
1. added a line to the subform
2. selected material
3. saved module parameters 
4. returned to step 1 if necessary
